### ISSUE TITLE
Small bug in Car AirControl pitch lock

### ISSUE THREAD

**Issue by lucas-emery** [ZealanL/RocketSim#24]
The check in https://github.com/ZealanL/RocketSim/blob/b223d2d4d6895f7fbc5f859c84edb5ee710e6d7b/src/Sim/Car/Car.cpp#L606
should be updated to
```
if (_internalState.isFlipping && _internalState.flipTime < FLIP_PITCHLOCK_TIME)
```
Otherwise the pitchlock remains active for FLIP_PITCHLOCK_TIME even if isFlipping was set to false during SetState

**Comment by ZealanL** [comment]
Ah I see, this stems from when I added `isFlipping`.
Fixed in dev branch, thank you!
