### ISSUE TITLE
Small improvement to flip timer

### ISSUE THREAD

**Issue by lucas-emery** [ZealanL/RocketSim#25]
This section
https://github.com/ZealanL/RocketSim/blob/b223d2d4d6895f7fbc5f859c84edb5ee710e6d7b/src/Sim/Car/Car.cpp#L726-L729

Could be changed to
```
if (_internalState.isFlipping) { 
```
So the timer stops counting after the flip is done

**Comment by ZealanL** [comment]
Yet another slight bug from adding `isFlipping`.
Fixed in dev branch, thank you!
